name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test GitHub Action
        run: echo "GitHub Action triggered successfully!"
